import { addArticleJsonLd } from '@/utils/seo/addArticleJsonLd';
import { getAutogeneratedPostOG } from '@/utils/social/og';
import { GetStaticPaths, GetStaticProps } from 'next';
import Head from 'next/head';
import Link from 'next/link';
import { useEffect, useRef, useState } from 'react';
import { FaBookOpen, FaGithub, FaLinkedinIn } from 'react-icons/fa';
import { SiHashnode } from 'react-icons/si';

import { BlogCard } from '@/components/blogs/BlogCard';
import { Container } from '@/components/container';
import { AppProvider } from '@/components/contexts/appContext';
import { Layout } from '@/components/layout';
import { MarkdownToHtml } from '@/components/markdown-to-html';
import { getAllPosts, getPostBySlug } from '@/lib/local-blogs';
import { getPublicationData } from '@/lib/local-publication';
import type { Post, Publication, StaticPage } from '@/lib/types';

// @ts-ignore
import handleMathJax from '@/utils/handle-math-jax';
import { useEmbeds } from '@/utils/renderer/hooks/useEmbeds';
import { loadIframeResizer } from '@/utils/renderer/services/embed';

type PostProps = {
	type: 'post';
	post: Post;
	publication: Publication;
	relatedPosts: Post[];
};

type PageProps = {
	type: 'page';
	page: StaticPage;
	publication: Publication;
};

type Props = PostProps | PageProps;

// Main Post Page Component
const PostComponent = ({ publication, post, relatedPosts }: PostProps) => {
	const highlightJsMonokaiTheme =
		'.hljs{display:block;overflow-x:auto;padding:.5em;background:#23241f}.hljs,.hljs-subst,.hljs-tag{color:#f8f8f2}.hljs-emphasis,.hljs-strong{color:#a8a8a2}.hljs-bullet,.hljs-link,.hljs-literal,.hljs-number,.hljs-quote,.hljs-regexp{color:#ae81ff}.hljs-code,.hljs-section,.hljs-selector-class,.hljs-title{color:#a6e22e}.hljs-strong{font-weight:700}.hljs-emphasis{font-style:italic}.hljs-attr,.hljs-keyword,.hljs-name,.hljs-selector-tag{color:#f92672}.hljs-attribute,.hljs-symbol{color:#66d9ef}.hljs-class .hljs-title,.hljs-params{color:#f8f8f2}.hljs-addition,.hljs-built_in,.hljs-builtin-name,.hljs-selector-attr,.hljs-selector-id,.hljs-selector-pseudo,.hljs-string,.hljs-template-variable,.hljs-type,.hljs-variable{color:#e6db74}.hljs-comment,.hljs-deletion,.hljs-meta{color:#75715e}';

	const socials = [
		{
			name: 'GitHub',
			href: publication.links?.github || 'https://github.com/kansal-anmol',
			icon: FaGithub,
		},
		{
			name: 'LinkedIn',
			href: publication.links?.linkedin || 'https://www.linkedin.com/in/kansal-anmol/',
			icon: FaLinkedinIn,
		},
		{
			name: 'Hashnode',
			href: publication.links?.hashnode || 'https://hashnode.com/@kansalanmol0609',
			icon: SiHashnode,
		},
	];

	const [canLoadEmbeds, setCanLoadEmbeds] = useState(false);
	const [activeHeadingId, setActiveHeadingId] = useState('');
	const [isMobileToCOpen, setIsMobileToCOpen] = useState(false);
	const [progress, setProgress] = useState(0);

	const articleRef = useRef<HTMLDivElement>(null);
	const authorCardRef = useRef<HTMLDivElement>(null);

	useEmbeds({ enabled: canLoadEmbeds });

	if (post.hasLatexInPost) {
		setTimeout(() => {
			handleMathJax(true);
		}, 500);
	}

	// Performance scaleX scroll progress tracker
	useEffect(() => {
		const handleScroll = () => {
			if (!articleRef.current) return;

			const rect = articleRef.current.getBoundingClientRect();
			const elementHeight = rect.height;
			const scrollPos = -rect.top;
			const windowHeight = window.innerHeight;

			// Stop tracking at the bottom of the article (start of the author card)
			const totalScrollable = elementHeight - windowHeight;

			if (totalScrollable <= 0) {
				setProgress(0);
				return;
			}

			let pct = scrollPos / totalScrollable;
			if (pct < 0) pct = 0;
			if (pct > 1) pct = 1;
			setProgress(pct);
		};

		window.addEventListener('scroll', handleScroll, { passive: true });
		window.addEventListener('resize', handleScroll);
		handleScroll();

		return () => {
			window.removeEventListener('scroll', handleScroll);
			window.removeEventListener('resize', handleScroll);
		};
	}, [post]);

	// Heading elements Intersection Observer for active ToC highlight
	useEffect(() => {
		const tocItems = post.features?.tableOfContents?.items;
		if (!tocItems || tocItems.length === 0) return;

		const observer = new IntersectionObserver(
			(entries) => {
				const visible = entries.filter((entry) => entry.isIntersecting);
				if (visible.length > 0) {
					setActiveHeadingId(visible[0].target.id);
				}
			},
			{
				rootMargin: '-80px 0px -60% 0px',
				threshold: 0.1,
			},
		);

		tocItems.forEach((item) => {
			const el = document.getElementById(item.slug);
			if (el) observer.observe(el);
		});

		return () => observer.disconnect();
	}, [post]);

	useEffect(() => {
		(async () => {
			await loadIframeResizer();
			setCanLoadEmbeds(true);
		})();
	}, []);

	const formatDate = (dateStr: string) => {
		return new Date(dateStr).toLocaleDateString('en-US', {
			month: 'short',
			day: 'numeric',
			year: 'numeric',
		});
	};

	const tocItems = post.features?.tableOfContents?.items || [];
	const primaryTag = post.tags?.[0]?.name || 'Engineering';

	return (
		<>
			<Head>
				<title>{post.seo?.title || post.title} — Anmol Kansal</title>
				<link rel="canonical" href={post.url || undefined} />
				<meta name="description" content={post.seo?.description || post.subtitle || post.brief} />
				<meta property="twitter:card" content="summary_large_image" />
				<meta property="twitter:title" content={post.seo?.title || post.title} />
				<meta
					property="twitter:description"
					content={post.seo?.description || post.subtitle || post.brief}
				/>
				<meta
					property="og:image"
					content={
						post.ogMetaData?.image ||
						post.coverImage?.url ||
						getAutogeneratedPostOG(post, publication)
					}
				/>
				<meta
					property="twitter:image"
					content={
						post.ogMetaData?.image ||
						post.coverImage?.url ||
						getAutogeneratedPostOG(post, publication)
					}
				/>
				<script
					type="application/ld+json"
					dangerouslySetInnerHTML={{
						__html: JSON.stringify(addArticleJsonLd(publication, post)),
					}}
				/>
				<style dangerouslySetInnerHTML={{ __html: highlightJsMonokaiTheme }}></style>
			</Head>

			{/* Scrolling progress bar fixed at viewport top */}
			<div
				style={{
					position: 'fixed',
					top: 0,
					left: 0,
					width: '100%',
					height: '2.5px',
					backgroundColor: '#b5f542',
					zIndex: 100,
					transform: `scaleX(${progress})`,
					transformOrigin: 'left',
					transition: 'transform 0.1s ease-out',
				}}
			/>

			{/* Main Article & Sidebar Two-Column Layout */}
			<div className="flex w-full flex-col gap-10">
				{/* Post Header */}
				<header className="flex w-full flex-col gap-5">
					{/* Breadcrumb */}
					<nav className="font-heading flex items-center gap-1.5 text-xs font-semibold tracking-wider text-neutral-500 uppercase select-none">
						<Link href="/blogs" className="transition-colors hover:text-[#b5f542]">
							Blog
						</Link>
						<span>→</span>
						<span className="max-w-[200px] truncate text-neutral-300 sm:max-w-xs">
							{post.title}
						</span>
					</nav>

					{/* 16:9 Cover Image */}
					<div className="relative aspect-video w-full overflow-hidden rounded-2xl border border-[#222222] bg-[#111111] shadow-md">
						<img
							src={
								post.coverImage?.url ||
								'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?q=80&w=1200&auto=format&fit=crop'
							}
							alt={post.title}
							className="h-full w-full object-cover"
						/>
					</div>

					{/* Title */}
					<h1 className="font-heading text-3xl leading-tight font-black tracking-tight text-white sm:text-4xl lg:text-5xl">
						{post.title}
					</h1>

					{/* Meta Row */}
					<div className="flex items-center gap-2.5 border-b border-[#222222] pb-6 text-xs font-semibold text-neutral-400 select-none">
						<img
							src={publication.author.profilePicture || '/assets/profile.jpg'}
							alt={publication.author.name}
							className="h-6 w-6 rounded-full border border-[#222222]"
						/>
						<span>Anmol Kansal</span>
						<span className="text-neutral-700">•</span>
						<span>{formatDate(post.publishedAt)}</span>
						<span className="text-neutral-700">•</span>
						<span>{post.readTimeInMinutes} min read</span>
					</div>
				</header>

				{/* Two-Column split container */}
				<div className="relative flex w-full flex-col items-start gap-12 lg:flex-row">
					{/* Left Content Column */}
					<div ref={articleRef} className="w-full max-w-2xl flex-1">
						<div className="prose prose-invert prose-custom max-w-none break-words">
							<MarkdownToHtml contentMarkdown={post.content?.markdown || ''} />
						</div>

						{/* Bottom Tags */}
						{post.tags && post.tags.length > 0 && (
							<div className="mt-12 border-t border-[#222222] pt-8">
								<h3 className="font-heading mb-4 text-sm font-bold tracking-widest text-neutral-300 uppercase">
									Tagged In
								</h3>
								<div className="flex flex-wrap gap-2">
									{post.tags.map((t) => (
										<Link
											key={t.id}
											href={`/blogs?tag=${encodeURIComponent(t.name)}`}
											onClick={() => {
												localStorage.setItem('selected_tag', t.name);
											}}
											className="rounded-md border border-[#333333] bg-[#161616] px-3 py-1.5 text-[11px] font-bold tracking-wide text-neutral-400 uppercase transition-all duration-300 hover:border-[#b5f542] hover:text-[#b5f542]"
										>
											{t.name}
										</Link>
									))}
								</div>
							</div>
						)}
					</div>

					{/* Right ToC Column (Desktop Sticky Sidebar) */}
					{tocItems.length > 0 && (
						<aside className="sticky top-24 hidden max-h-[calc(100vh-120px)] w-64 shrink-0 scrollbar-none overflow-y-auto select-none lg:block">
							<div className="flex flex-col gap-4 border-l border-[#222222] pl-4">
								<h4 className="font-heading text-[10px] font-bold tracking-widest text-neutral-400 uppercase">
									ON THIS PAGE
								</h4>
								<ul className="flex flex-col gap-3">
									{tocItems.map((item) => {
										const isH3 = item.level === 3;
										const isActive = item.slug === activeHeadingId;
										return (
											<li
												key={item.id}
												style={{ paddingLeft: isH3 ? '12px' : '0px' }}
												className="relative"
											>
												{isActive && (
													<span className="absolute top-[5px] -left-[17px] h-3 w-[2.5px] bg-[#b5f542]" />
												)}
												<a
													href={`#${item.slug}`}
													className={`font-heading block text-xs font-semibold transition-colors duration-200 ${
														isActive ? 'text-[#b5f542]' : 'text-neutral-400 hover:text-white'
													}`}
												>
													{item.title}
												</a>
											</li>
										);
									})}
								</ul>
							</div>
						</aside>
					)}
				</div>

				{/* Collapsible Mobile ToC Drawer */}
				{tocItems.length > 0 && (
					<div className="lg:hidden">
						{/* Floating Trigger button */}
						<button
							onClick={() => setIsMobileToCOpen(true)}
							className="font-heading fixed right-6 bottom-6 z-50 flex items-center gap-2 rounded-full border border-[#222222] bg-[#111111] px-4 py-2.5 text-xs font-bold text-[#b5f542] shadow-2xl transition-all duration-300 hover:border-[#b5f542]"
						>
							<FaBookOpen className="h-3.5 w-3.5" />
							Contents
						</button>

						{/* Overlay & Drawer body */}
						{isMobileToCOpen && (
							<>
								<div
									onClick={() => setIsMobileToCOpen(false)}
									className="animate-fadeIn fixed inset-0 z-50 bg-black/60 backdrop-blur-sm"
								/>
								<div className="animate-slideUp fixed right-0 bottom-0 left-0 z-50 max-h-[60vh] overflow-y-auto rounded-t-3xl border-t border-[#222222] bg-[#0a0a0a] px-6 pt-5 pb-8 select-none">
									<div className="mb-4 flex items-center justify-between border-b border-[#222222] pb-3">
										<h4 className="font-heading text-xs font-bold tracking-widest text-neutral-400 uppercase">
											ON THIS PAGE
										</h4>
										<button
											onClick={() => setIsMobileToCOpen(false)}
											className="text-sm font-bold text-neutral-500 hover:text-white focus:outline-none"
										>
											Close
										</button>
									</div>
									<ul className="flex flex-col gap-3.5">
										{tocItems.map((item) => {
											const isH3 = item.level === 3;
											const isActive = item.slug === activeHeadingId;
											return (
												<li key={item.id} style={{ paddingLeft: isH3 ? '12px' : '0px' }}>
													<a
														href={`#${item.slug}`}
														onClick={() => setIsMobileToCOpen(false)}
														className={`font-heading block text-sm font-semibold ${
															isActive ? 'text-[#b5f542]' : 'text-neutral-400'
														}`}
													>
														{item.title}
													</a>
												</li>
											);
										})}
									</ul>
								</div>
							</>
						)}
					</div>
				)}

				{/* Author Card (below post content, above related posts) */}
				<div
					ref={authorCardRef}
					className="mt-8 flex w-full flex-col items-center gap-6 rounded-xl border border-[#222222] bg-[#111111] p-6 text-center md:flex-row md:items-start md:text-left"
				>
					<div className="h-[64px] w-[64px] shrink-0 overflow-hidden rounded-full border border-[#222222] bg-[#0a0a0a]">
						<img
							src={publication.author.profilePicture || '/assets/profile.jpg'}
							alt="Anmol Kansal"
							className="h-full w-full object-cover"
						/>
					</div>
					<div className="flex flex-grow flex-col gap-3">
						<div className="flex flex-col gap-0.5">
							<h4 className="font-heading text-md font-extrabold text-white">Anmol Kansal</h4>
							<p className="font-heading text-xs font-semibold tracking-wider text-[#b5f542] uppercase">
								Senior Frontend Engineer @ D.E. Shaw
							</p>
						</div>
						<p className="font-body max-w-xl text-sm leading-relaxed text-neutral-400">
							Full stack developer with 4+ years building scalable web products. I write about
							TypeScript, React, and frontend systems.
						</p>

						{/* Icon links row below bio */}
						<div className="mt-1.5 flex items-center justify-center gap-3 md:justify-start">
							{socials.map((social) => {
								const Icon = social.icon;
								return (
									<a
										key={social.name}
										href={social.href}
										target="_blank"
										rel="noopener noreferrer"
										aria-label={`Visit my ${social.name}`}
										className="text-neutral-500 transition-colors duration-300 hover:text-[#b5f542]"
									>
										<Icon className="h-5 w-5" />
									</a>
								);
							})}
						</div>
					</div>
				</div>

				{/* Related Posts */}
				{relatedPosts.length > 0 && (
					<section className="mt-6 flex flex-col gap-6 border-t border-[#222222] pt-12">
						<h3 className="font-heading text-xl font-black tracking-tight text-white">
							More posts
						</h3>
						<div className="grid grid-cols-1 gap-6 sm:grid-cols-3">
							{relatedPosts.map((post) => (
								<BlogCard key={post.id} post={post} />
							))}
						</div>
					</section>
				)}
			</div>
		</>
	);
};

// Main Page Route Component
const PageComponent = ({ page }: PageProps) => {
	const title = page.title;
	return (
		<>
			<Head>
				<title>{title} — Anmol Kansal</title>
			</Head>
			<div className="prose prose-invert prose-custom w-full max-w-none">
				<MarkdownToHtml contentMarkdown={page.content.markdown} />
			</div>
		</>
	);
};

export default function PostOrPage(props: Props) {
	const [isMobileMenuOpen, setIsMobileMenuOpen] = useState(false);
	const maybePost = props.type === 'post' ? props.post : null;
	const maybePage = props.type === 'page' ? props.page : null;
	const publication = props.publication;

	const socials = [
		{
			name: 'GitHub',
			href: publication.links?.github || 'https://github.com/kansal-anmol',
			icon: FaGithub,
		},
		{
			name: 'LinkedIn',
			href: publication.links?.linkedin || 'https://www.linkedin.com/in/kansal-anmol/',
			icon: FaLinkedinIn,
		},
		{
			name: 'Hashnode',
			href: publication.links?.hashnode || 'https://hashnode.com/@kansalanmol0609',
			icon: SiHashnode,
		},
	];

	return (
		<AppProvider publication={publication} post={maybePost} page={maybePage}>
			<Layout>
				{/* Blogs Post Page Outer Container in Dark Mode */}
				<div className="dark font-body min-h-screen bg-[#0a0a0a] text-neutral-100 selection:bg-[#b5f542]/20 selection:text-[#b5f542]">
					{/* Navbar */}
					<nav className="sticky top-0 z-50 border-b border-[#222222] bg-[#0a0a0a]/80 backdrop-blur-md">
						<div className="mx-auto flex h-16 max-w-6xl items-center justify-between px-6">
							{/* Logo / Monogram */}
							<Link href="/" className="group flex items-center gap-2">
								<div className="relative flex h-9 w-9 items-center justify-center overflow-hidden rounded-lg border border-[#222222] transition-all duration-300 group-hover:border-[#b5f542] group-hover:shadow-[0_0_10px_rgba(181,245,66,0.15)]">
									<img
										src="/assets/profile.jpg"
										alt="Anmol Kansal"
										className="h-full w-full object-cover"
									/>
								</div>
							</Link>

							{/* Desktop Nav Links */}
							<div className="hidden items-center gap-8 md:flex">
								<Link
									href="/"
									className="font-heading text-sm font-medium text-neutral-400 transition-colors hover:text-[#b5f542]"
								>
									Home
								</Link>
								<Link
									href="/about"
									className="font-heading text-sm font-medium text-neutral-400 transition-colors hover:text-[#b5f542]"
								>
									About
								</Link>
								<Link
									href="/blogs"
									className="font-heading text-sm font-semibold text-[#b5f542] transition-colors"
								>
									Blog
								</Link>
								<Link
									href="/terminal"
									className="font-heading text-sm font-medium text-neutral-400 transition-colors hover:text-[#b5f542]"
								>
									Terminal
								</Link>
							</div>

							{/* Mobile Hamburger Button */}
							<button
								onClick={() => setIsMobileMenuOpen(!isMobileMenuOpen)}
								className="p-2 text-neutral-400 hover:text-[#b5f542] focus:outline-none md:hidden"
								aria-label="Toggle Menu"
							>
								{isMobileMenuOpen ? (
									<svg className="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor">
										<path
											strokeLinecap="round"
											strokeLinejoin="round"
											strokeWidth={2}
											d="M6 18L18 6M6 6l12 12"
										/>
									</svg>
								) : (
									<svg className="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor">
										<path
											strokeLinecap="round"
											strokeLinejoin="round"
											strokeWidth={2}
											d="M4 6h16M4 12h16M4 18h16"
										/>
									</svg>
								)}
							</button>
						</div>

						{/* Mobile Nav Menu */}
						{isMobileMenuOpen && (
							<div className="flex flex-col gap-4 border-b border-[#222222] bg-[#0a0a0a] px-6 py-4 md:hidden">
								<Link
									href="/"
									onClick={() => setIsMobileMenuOpen(false)}
									className="font-heading py-1 text-sm font-medium text-neutral-400 transition-colors hover:text-[#b5f542]"
								>
									Home
								</Link>
								<Link
									href="/about"
									onClick={() => setIsMobileMenuOpen(false)}
									className="font-heading py-1 text-sm font-medium text-neutral-400 transition-colors hover:text-[#b5f542]"
								>
									About
								</Link>
								<Link
									href="/blogs"
									onClick={() => setIsMobileMenuOpen(false)}
									className="font-heading py-1 text-sm font-semibold text-[#b5f542]"
								>
									Blog
								</Link>
								<Link
									href="/terminal"
									onClick={() => setIsMobileMenuOpen(false)}
									className="font-heading py-1 text-sm font-medium text-neutral-400 transition-colors hover:text-[#b5f542]"
								>
									Terminal
								</Link>
							</div>
						)}
					</nav>

					{/* Main Blog Post Content Layout */}
					<Container className="mx-auto max-w-4xl px-6 pt-10">
						<article className="flex flex-col items-start gap-10 pb-20">
							{props.type === 'post' && <PostComponent {...props} />}
							{props.type === 'page' && <PageComponent {...props} />}
						</article>
					</Container>

					{/* Footer */}
					<footer className="border-t border-[#222222] bg-[#0a0a0a] py-12">
						<div className="mx-auto flex max-w-6xl flex-col items-center justify-center gap-6 px-6">
							<div className="flex items-center gap-4">
								{socials.map((social) => {
									const Icon = social.icon;
									return (
										<a
											key={social.name}
											href={social.href}
											target="_blank"
											rel="noopener noreferrer"
											aria-label={`Visit my ${social.name}`}
											className="text-neutral-500 transition-colors duration-300 hover:text-[#b5f542]"
										>
											<Icon className="h-5 w-5" />
										</a>
									);
								})}
							</div>
							<p className="font-heading text-sm font-medium text-neutral-500">
								© 2025 Anmol Kansal
							</p>
						</div>
					</footer>
				</div>
			</Layout>
		</AppProvider>
	);
}

type Params = {
	blogId: string;
};

export const getStaticProps: GetStaticProps<Props, Params> = async ({ params }) => {
	if (!params) {
		throw new Error('No params');
	}

	const blogId = params.blogId;
	const post = await getPostBySlug(blogId);

	if (post) {
		const publication = getPublicationData();
		const allPosts = await getAllPosts();

		// Related posts: match tags
		const postTagsSet = new Set(post.tags?.map((t) => t.name.toLowerCase()) || []);
		let related = allPosts.filter(
			(p) => p.id !== post.id && p.tags?.some((t) => postTagsSet.has(t.name.toLowerCase())),
		);

		// Fallback to latest posts if fewer than 3
		if (related.length < 3) {
			const ids = new Set(related.map((p) => p.id));
			const fallbacks = allPosts.filter((p) => p.id !== post.id && !ids.has(p.id));
			related = [...related, ...fallbacks].slice(0, 3);
		} else {
			related = related.slice(0, 3);
		}

		return {
			props: {
				type: 'post',
				post,
				publication,
				relatedPosts: related,
			},
			revalidate: 60,
		};
	}

	return {
		notFound: true,
		revalidate: 60,
	};
};

export const getStaticPaths: GetStaticPaths = async () => {
	const posts = await getAllPosts();

	return {
		paths: posts.map((post) => {
			return {
				params: {
					blogId: post.slug,
				},
			};
		}),
		fallback: 'blocking',
	};
};
